SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS event_location;
DROP TABLE IF EXISTS event_user;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS picture;
DROP TABLE IF EXISTS rating;
DROP TABLE IF EXISTS rso;
DROP TABLE IF EXISTS rso_user;
DROP TABLE IF EXISTS university;
DROP TABLE IF EXISTS university_event;
DROP TABLE IF EXISTS university_location;
DROP TABLE IF EXISTS university_picture;
DROP TABLE IF EXISTS university_rso;
DROP TABLE IF EXISTS user;

SET FOREIGN_KEY_CHECKS = 1;